extraction:
  cpp:
    after_prepare: 
      - python report.py 6
  cobol:
    after_prepare: 
      - python report.py 6
  csharp:
    after_prepare: 
      - python report.py 6
  java:
    after_prepare: 
      - python report.py 6
  javascript:
    after_prepare: 
      - python report.py 6
  python:
    after_prepare: 
      - python report.py 6
